### PR TITLE
All examples are python3 and python2 compatible

### PR DESCRIPTION
**Pull request by katiabazzi**

### CODE REVIEW

**Comment by carlosalberto** [comment]
For some reason, `tox` cannot get Python 3.4 for me, so I used:

```
[tox]
; envlist = py26, py27, py34
envlist = py27,py36
```

And this causes for `3.6` (but not for `2.7`):

```
[LightStep Tracer]:  Caught exception during report: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749), stack trace: Traceback (most recent call last):
  File "/development/lightstep-tracer-python/.tox/py36/lib/python3.6/site-packages/lightstep/recorder.py", line 277, in _flush_worker
    resp = connection.report(self._auth, report_request)
  File "/development/lightstep-tracer-python/.tox/py36/lib/python3.6/site-packages/lightstep/connection.py", line 62, in report
    resp = self._client.Report(*args, **kwargs)
  File "/development/lightstep-tracer-python/.tox/py36/lib/python3.6/site-packages/lightstep/crouton/ReportingService.py", line 44, in Report
    self.send_Report(auth, request)
  File "/development/lightstep-tracer-python/.tox/py36/lib/python3.6/site-packages/lightstep/crouton/ReportingService.py", line 54, in send_Report
    self._oprot.trans.flush()
  File "/development/lightstep-tracer-python/.tox/py36/lib/python3.6/site-packages/thrift/transport/THttpClient.py", line 141, in _f
    result = f(*args, **kwargs)
  File "/development/lightstep-tracer-python/.tox/py36/lib/python3.6/site-packages/thrift/transport/THttpClient.py", line 181, in flush
    self.__http.endheaders()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
```

Wondering if this is caused by a change from `3.4` -> `3.6` in the Python API.

**Comment by katiabazzi** [comment]
@carlosalberto It worked for me and Sarah once we switched to Python 3.4.3 locally via `pyenv`

**Comment by carlosalberto** [comment]
Nevermind, updated tox and now it's using it. So no problem, everything looks nice ;) So if I'm correct, the plan is to support Python 2.7 *and* 3.4 specifically, right?

**Comment by katiabazzi** [comment]
Nice! It looks like we've been supporting Python 2.7 and 3.4, but I'm not sure if there are more versions we should support. Probably a better question for @tedsuo

**Pull request merged**
